version: "3.9"

services:
  redis:
    image: redis:7.2
    container_name: redis-mcp
    ports:
      - "6379:6379"
    restart: always

  mongo:
    image: mongo:6.0
    container_name: mongo-mcp
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
